Repository devvsakib/Frontend-Projects, pull requests merged in 2022-10, with the labels that each got.

#8 added Email-client-app
  Email-Client-App/app.min.css
  Email-Client-App/app.min.js
  Email-Client-App/index.html
  Email-Client-App/zepto.js
Labels: hacktoberfest, hacktoberfest-accepted

#14 Added website designs
  Website designs/index.css
  Website designs/index.html
  Website designs/style.html
  Website designs/style1.html
  Website designs/style2.html
  Website designs/style3.html
  Website designs/style4.html
Labels: hacktoberfest, hacktoberfest-accepted

#20 changes done you can check pls merge it now thank you
  eduford uni/css/about.css
  eduford uni/css/blog.css
  eduford uni/css/contact.css
  eduford uni/css/courses.css
  eduford uni/css/home.css
  eduford uni/html/about.html
  eduford uni/html/blog.html
  eduford uni/html/contact.html
  eduford uni/html/courses.html
  eduford uni/html/home.html
  eduford uni/images/Facebook_icon.svg.png
  eduford uni/images/Instagram_logo_2016.svg.png
  eduford uni/images/about.jpg
  eduford uni/images/background.jpg
  eduford uni/images/banner.png
  eduford uni/images/banner2.jpg
  eduford uni/images/basketball.png
  eduford uni/images/cafeteria.png
  eduford uni/images/certificate.jpg
  eduford uni/images/library.png
  eduford uni/images/linkedin-icon-logo-png-transparent.png
  eduford uni/images/logo.png
  eduford uni/images/london.png
  eduford uni/images/newyork.png
  eduford uni/images/twitter-logo-2-1.png
  eduford uni/images/user1.jpg
  eduford uni/images/user2.jpg
  eduford uni/images/washington.png
Labels: hacktoberfest-accepted

#31 Solar Company Website
  Solar Company Website/P7.css
  Solar Company Website/Solartec company.html
  Solar Company Website/american-public-power-association-XGAZzyLzn18-unsplash.jpg
  Solar Company Website/andreas-gucklhorn-Ilpf2eUPpUE-unsplash.jpg
  Solar Company Website/article_wind_and_solar_main-760x378.jpg
  Solar Company Website/bill-mead-wmaP3Tl80ww-unsplash (1).jpg
  Solar Company Website/check.png
  Solar Company Website/emmanuel-ikwuegbu-zWOgsj3j0wA-unsplash.jpg
  Solar Company Website/frederic-paulussen-LWnD8U2OReU-unsplash.jpg
  Solar Company Website/jadon-kelly-Y-4LPhF4giI-unsplash.jpg
  Solar Company Website/largermug.jpg
  Solar Company Website/male2.jfif
  Solar Company Website/male22.heic
  Solar Company Website/manny-becerra-NgdhrwAx0J8-unsplash.jpg
  Solar Company Website/raphael-cruz-IwY-27ceRCA-unsplash.jpg
  Solar Company Website/shyam.jpg
  Solar Company Website/waldemar-brandt-8NBACfGMFtw-unsplash.jpg
  Solar2022/Solar.css
  Solar2022/Solartec Company.html
  Solar2022/images/american-public-power-association-XGAZzyLzn18-unsplash.jpg
  Solar2022/images/andreas-gucklhorn-Ilpf2eUPpUE-unsplash.jpg
  Solar2022/images/article_wind_and_solar_main-760x378.jpg
  Solar2022/images/bill-mead-wmaP3Tl80ww-unsplash (1).jpg
  Solar2022/images/check.png
  Solar2022/images/emmanuel-ikwuegbu-zWOgsj3j0wA-unsplash.jpg
  Solar2022/images/frederic-paulussen-LWnD8U2OReU-unsplash.jpg
  Solar2022/images/jadon-kelly-Y-4LPhF4giI-unsplash.jpg
  Solar2022/images/largermug.jpg
  Solar2022/images/male2.jfif
  Solar2022/images/male22.heic
  Solar2022/images/manny-becerra-NgdhrwAx0J8-unsplash.jpg
  Solar2022/images/raphael-cruz-IwY-27ceRCA-unsplash.jpg
  Solar2022/images/shyam.jpg
  Solar2022/images/waldemar-brandt-8NBACfGMFtw-unsplash.jpg
Labels: hacktoberfest

#48 add(Frontend Project):added login form
  Login Form/images/bg1.jpg
  Login Form/images/bg2.jpg
  Login Form/index.html
  Login Form/script.js
  Login Form/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#56 required changees done
  main/Frontend-Projects/index.html
Labels: good first issue, hacktoberfest
